# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8354ce96e8baa41dd397b41f48852cd8c170aa8b968a39dcf4f708ea3ed134e3e5666c4686547f1bbe26b1a0e9a7d2f57146368a22b859401a3448fb56402918

test:
  secret_key_base: 0b53e3af9c2bd2815d17d208176b58102a630fa64c5fc503a0a38b061fa03435274465594fa11effa25db249881ef211b9c3cf24fe763f32ba85f3cb50a01245

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
